import test from 'node:test';
import assert from 'node:assert/strict';
import {MinecraftBlockTypes} from '@minecraft/vanilla-data';
import {newMiner,miner,hitNode,NODES,ORES,capacity,load,value,upgrade,sell,unload,chamberCommands,stamp,roomAt} from '../pack/scripts/mining.js';
test('hardness decreases per strike and broken node cannot pay out twice',()=>{const m=newMiner(),n=NODES[2],d={hp:ORES[n.ore].hp,regen:0};for(let i=0;i<4;i++)assert.equal(hitNode(m,n,d,50,100).broken,false);assert.ok(hitNode(m,n,d,50,100).broken);assert.equal(m.bag.copper,1);assert.equal(d.regen,160);assert.equal(hitNode(m,n,d,50,100).ok,false);assert.equal(m.bag.copper,1);});
test('capacity, tier and energy checks do not consume node hardness',()=>{const m=newMiner(),n=NODES[5],d={hp:1,regen:0};m.bag.stone=19;assert.equal(hitNode(m,n,d,100,1).ok,false);assert.equal(d.hp,1);m.bag={};assert.equal(hitNode(m,n,d,0,1).ok,false);assert.equal(hitNode(m,NODES[6],d,100,1).ok,false);assert.equal(d.hp,1);});
test('upgrades charge shared gold and increase damage or capacity',()=>{const m=newMiner(),farm={gold:500};assert.ok(upgrade(m,farm,'pick'));assert.equal(farm.gold,400);assert.equal(m.pick,1);assert.ok(upgrade(m,farm,'bag'));assert.equal(capacity(m),40);const d={hp:5,regen:0};hitNode(m,NODES[2],d,50,1);assert.equal(d.hp,3);farm.gold=0;assert.equal(upgrade(m,farm,'pick'),false);assert.equal(m.pick,1);});
test('selling and material storage cannot duplicate ore',()=>{const m=newMiner(),farm={gold:0,bag:{}};m.bag={gold:2,diamond:1};assert.equal(value(m),200);assert.equal(sell(m,farm),200);assert.equal(sell(m,farm),0);assert.equal(farm.gold,200);m.bag={copper:3};unload(m,farm);unload(m,farm);assert.equal(farm.bag.copper,3);assert.equal(load(m),0);});
test('miner persists across reconnects and rejects invalid profiles',()=>{const m=newMiner();m.pick=3;m.bag.diamond=2;assert.deepEqual(miner(JSON.stringify(m)),m);assert.deepEqual(miner('{broken'),newMiner());assert.deepEqual(miner(JSON.stringify({...m,pick:8})),newMiner());});
test('mine rooms stay below farm with registered blocks and safe fill sizes',()=>{const known=new Set(Object.values(MinecraftBlockTypes));for(const cmd of chamberCommands()){const t=cmd.split(' '),[x,y,z,a,b,c]=t.slice(1,7).map(Number);assert.ok(y>=169&&b<190);assert.ok((a-x+1)*(b-y+1)*(c-z+1)<32768);assert.ok(known.has('minecraft:'+t.at(-1)));}for(const n of NODES){assert.equal(roomAt(n),n.room);assert.ok(known.has('minecraft:'+ORES[n.ore].block));}assert.equal(roomAt({x:169,y:201,z:12}),-1);assert.equal(NODES.length,24);assert.equal(new Set(NODES.map(n=>`${n.x},${n.y},${n.z}`)).size,24);});
test('mine cooldown uses saved calendar time across day and season rollover',()=>{assert.ok(stamp({year:1,season:1,day:1,minute:360})>stamp({year:1,season:0,day:28,minute:1550}));});

test('dirt is easier and less valuable than stone and gold',()=>{assert.equal(ORES.dirt.hp,1);assert.ok(ORES.dirt.hp<ORES.stone.hp&&ORES.stone.hp<ORES.gold.hp);assert.ok(ORES.dirt.sell<ORES.stone.sell&&ORES.stone.sell<ORES.gold.sell);const m=newMiner(),n=NODES[0];assert.ok(hitNode(m,n,{hp:1,regen:0},100,0).broken);assert.equal(m.bag.dirt,1);});
