server-name=jinjiazh
# iPad / 基岩版客户端里显示的房间名

gamemode=survival
force-gamemode=false
difficulty=normal
allow-cheats=true
max-players=8

online-mode=true
allow-list=false

server-port=19132
server-portv6=19133
# 1.26.30+ 关掉这项会回空 pong，客户端报 Kelp 超时
enable-lan-visibility=true
transport=raknet

# 2G 内存机器，视距不要用官方默认 32
view-distance=8
tick-distance=4
player-idle-timeout=0
max-threads=2

level-name=world
level-seed=
default-player-permission-level=member
texturepack-required=false

compression-threshold=1
compression-algorithm=zlib
client-side-chunk-generation-enabled=true
disable-custom-skins=false
chat-restriction=None
disable-player-interaction=false
