import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as rules from '../pack/scripts/rules.js';
import {courtyard} from '../pack/scripts/scenery.js';
function harness(){
 const properties=new Map(),players=[],blocks=new Map(),events={};let currentRound=rules.newRound(1,77);currentRound.generated=32;
 class ItemStack{constructor(id,n=1){this.typeId=id;this.amount=n;}setLore(){}}
 class Form{title(){return this}body(){return this}button(){return this}async show(){return {canceled:false,selection:0}}}
 const event=n=>({subscribe:fn=>events[n]=fn});
 const dim={id:'minecraft:overworld',getBlock:q=>{const k=`${q.x},${q.y},${q.z}`;if(!blocks.has(k))blocks.set(k,{location:q,typeId:rules.MATERIALS[rules.materialAt(q,currentRound)].block,isLiquid:false,setType(id){this.typeId=id;},setPermutation(p){this.typeId=p.typeId;}});return blocks.get(k)},getEntities:()=>[],runCommand(){}};
 const world={getDimension:()=>dim,getAllPlayers:()=>players,getDynamicProperty:k=>properties.get(k),setDynamicProperty:(k,v)=>properties.set(k,v),sendMessage(){},afterEvents:{itemStartUse:event('start'),itemStopUse:event('stop'),playerSpawn:event('spawn'),playerLeave:event('leave'),worldLoad:event('load')},beforeEvents:{playerInteractWithBlock:event('block')}};
 const system={currentTick:0,run:fn=>fn(),runTimeout(){},runInterval(){return 1},clearRun(){},beforeEvents:{startup:event('startup')},afterEvents:{scriptEventReceive:event('script')}};
 const ctx=vm.createContext({...rules,courtyard,world,system,ItemStack,ActionFormData:Form,ItemLockMode:{inventory:'inventory'},GameMode:{Adventure:'adventure'},BlockPermutation:{resolve:id=>({typeId:id})},console});
 const source=fs.readFileSync(new URL('../pack/scripts/main.js',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
 vm.runInContext(source+'\nglobalThis.api={fillSegment,mine,interact,exchange,flush,held,round:()=>round,enable(r){round=r;ready=true},data};',ctx);ctx.api.enable(currentRound);
 function player(id,target=currentRound.rainbow){const props=new Map();props.set('rush:profile',JSON.stringify({...rules.newProfile(1),tier:5}));const slots=[new ItemStack('rush:pick_5')];const c={size:36,getItem:i=>slots[i],setItem:(i,v)=>slots[i]=v,addItem:item=>{const slot=Array.from({length:36},(_,i)=>i).find(i=>!slots[i]);if(slot===undefined)return item;slots[slot]=item;return undefined;}};
  const p={id,name:id,isValid:true,dimension:dim,location:{x:target.x,y:target.y,z:target.z-2},selectedSlotIndex:0,getDynamicProperty:k=>props.get(k),setDynamicProperty:(k,v)=>props.set(k,v),getComponent:()=>({container:c}),getBlockFromViewDirection:()=>({block:dim.getBlock(target)}),getViewDirection:()=>({x:0,y:0,z:1}),sendMessage(t){this.lastMessage=t},playSound(){},onScreenDisplay:{setActionBar(){},setTitle(){}},teleport(q){this.location=q},setGameMode(){},setSpawnPoint(){},addEffect(){},removeEffect(){}};players.push(p);return {p,c,slots};}
 return {api:ctx.api,player,players,dim,blocks,properties,events,round:currentRound};
}
test('full inventory prevents rainbow removal and victory; space permits exactly one winner',()=>{const h=harness(),a=h.player('Alice'),b=h.player('Bob');for(let i=1;i<36;i++)a.slots[i]={typeId:'minecraft:apple',amount:64};for(let i=0;i<4;i++)h.api.mine(a.p);assert.equal(h.api.round().winner,null);assert.equal(h.dim.getBlock(h.round.rainbow).typeId,'rush:rainbow_ore');a.slots[35]=undefined;h.api.mine(a.p);assert.equal(h.api.round().winner.id,'Alice');h.api.mine(b.p);assert.equal(b.slots.filter(i=>i?.typeId==='rush:rainbow_gem').length,0);assert.equal(a.slots.filter(i=>i?.typeId==='rush:rainbow_gem').length,1);});
test('exchanged items disappear and cannot pay twice',async()=>{const h=harness(),a=h.player('Alice');a.p.location={x:12,y:187,z:17};a.slots[1]={typeId:'minecraft:gold_block',amount:4};h.api.exchange(a.p);await new Promise(setImmediate);assert.equal(h.api.data(a.p).coins,480,a.p.lastMessage);assert.equal(a.slots[1],undefined);h.api.exchange(a.p);await new Promise(setImmediate);assert.equal(h.api.data(a.p).coins,480,a.p.lastMessage);});
test('quick touch release clears mining state without queued ghost input',()=>{const h=harness(),a=h.player('Alice');h.events.start({source:a.p,itemStack:{typeId:'rush:pick_5'}});h.events.stop({source:a.p});assert.equal(h.api.held.has(a.p.id),false);});
test('dug cells are persisted and replacement blocks cannot be farmed again',()=>{const h=harness(),q={x:30,y:188,z:60},a=h.player('Alice',q);h.dim.getBlock(q).setType('minecraft:dirt');h.api.mine(a.p);h.api.flush();const saved=h.properties.get('rush:dug_'+rules.segmentOf(q.z));assert.ok(rules.wasDug(rules.decodeBits(saved),rules.cellIndex(q)));h.dim.getBlock(q).setType('minecraft:gold_block');h.api.mine(a.p);assert.equal(a.slots.filter(i=>i?.typeId==='minecraft:gold_block').length,0);});

test('segment fills the old frontier last and marks entry air as already cleared',()=>{const h=harness(),work=h.api.fillSegment(0);work.next();assert.ok(h.blocks.has('16,180,41'));assert.equal(h.blocks.has('16,180,40'),false);let steps=1;while(!work.next().done){assert.ok(++steps<200);}assert.ok(h.blocks.has('16,180,40'));h.api.flush();const dug=rules.decodeBits(h.properties.get('rush:dug_0'));assert.ok(rules.wasDug(dug,rules.cellIndex({x:24,y:188,z:40})));assert.equal(h.dim.getBlock({x:24,y:188,z:40}).typeId,'minecraft:air');});
