"""Generate Bedrock definitions referencing vanilla textures, no external assets."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
BP=ROOT/'pack';RP=ROOT/'resource_pack'
def write(p,o):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(o,ensure_ascii=False,indent=2),encoding='utf-8')
write(BP/'manifest.json',{'format_version':2,'header':{'name':'末日赫尔辛基 · 搜集与撤离','description':'Linnanmäki 基地 / 火力升级 / 尸群 / 潜行撤离','uuid':'67bd555b-4036-40bc-b0ac-d44c3dd5d197','version':[1,0,1],'min_engine_version':[1,26,30]},'modules':[{'type':'data','uuid':'e48ddc68-839b-496b-bb7b-535928a2134d','version':[1,0,1]},{'type':'script','language':'javascript','uuid':'8a9b8f67-1a97-4f67-9d95-b8e21ea64b74','version':[1,0,1],'entry':'scripts/main.js'}],'dependencies':[{'module_name':'@minecraft/server','version':'2.1.0'},{'module_name':'@minecraft/server-ui','version':'2.0.0'},{'uuid':'35b4b949-a51c-4fa8-a6f3-bf43366f2875','version':[1,0,1]}]})
write(RP/'manifest.json',{'format_version':2,'header':{'name':'末日赫尔辛基 · 视觉','description':'四类感染者，使用原版纹理','uuid':'35b4b949-a51c-4fa8-a6f3-bf43366f2875','version':[1,0,1],'min_engine_version':[1,26,30]},'modules':[{'type':'resources','uuid':'c8768fa3-5b93-4726-b634-7c04d739c3bb','version':[1,0,1]}]})
for id,name,icon,seconds in [('gun','枪械 · 按住使用开火','crossbow_standby',3600),('radio','无线电 · 任务与升级','compass_item',3600),('reload','弹匣 · 使用换弹','iron_ingot',3600),('medkit','医疗包 · 使用治疗','apple',3600),('lure','声响诱饵 · 使用投掷','snowball',3600)]:
    write(BP/f'items/{id}.json',{'format_version':'1.26.30','minecraft:item':{'description':{'identifier':'dead:'+id,'menu_category':{'category':'equipment'}},'components':{'minecraft:display_name':{'value':name},'minecraft:icon':{'textures':{'default':icon}},'minecraft:max_stack_size':1,'minecraft:hand_equipped':id=='gun','minecraft:interact_button':{'gun':'开火','radio':'无线电','reload':'换弹','medkit':'治疗','lure':'诱饵'}[id],'minecraft:use_modifiers':{'use_duration':seconds,'movement_modifier':1},'minecraft:food':{'nutrition':0,'saturation_modifier':0,'can_always_eat':True},'minecraft:use_animation':'none'}}})
for id,hp,speed,damage,scale in [('walker',24,.19,3,1),('runner',18,.31,3,.88),('screamer',32,.20,2,1),('armored',110,.14,6,1.18)]:
    groups={'dead:calm':{'minecraft:behavior.random_stroll':{'priority':6,'speed_multiplier':.5}},'dead:alert':{'minecraft:behavior.nearest_attackable_target':{'priority':2,'must_see':True,'must_see_forget_duration':3,'within_radius':36,'entity_types':[{'filters':{'all_of':[{'test':'is_family','subject':'other','value':'player'},{'test':'has_tag','subject':'other','value':'dead_active'}]},'max_dist':36}]},'minecraft:behavior.melee_attack':{'priority':3,'speed_multiplier':1,'track_target':True}}}
    components={'minecraft:type_family':{'family':['dead','monster','mob']},'minecraft:health':{'value':hp,'max':hp},'minecraft:movement':{'value':speed},'minecraft:movement.basic':{},'minecraft:navigation.walk':{'can_path_over_water':False,'avoid_water':True,'can_open_doors':False,'can_pass_doors':True},'minecraft:jump.static':{},'minecraft:physics':{},'minecraft:pushable':{'is_pushable':True,'is_pushable_by_piston':True},'minecraft:collision_box':{'width':.6,'height':1.8},'minecraft:attack':{'damage':damage},'minecraft:scale':{'value':scale},'minecraft:follow_range':{'value':40},'minecraft:behavior.float':{'priority':0},'minecraft:nameable':{},'minecraft:persistent':{}}
    write(BP/f'entities/{id}.json',{'format_version':'1.21.90','minecraft:entity':{'description':{'identifier':'dead:'+id,'is_spawnable':True,'is_summonable':True,'is_experimental':False},'component_groups':groups,'components':components,'events':{'minecraft:entity_spawned':{'add':{'component_groups':['dead:calm']}},'dead:alert':{'remove':{'component_groups':['dead:calm']},'add':{'component_groups':['dead:alert']}},'dead:calm':{'remove':{'component_groups':['dead:alert']},'add':{'component_groups':['dead:calm']}}}}})
    write(RP/f'entity/{id}.entity.json',{'format_version':'1.10.0','minecraft:client_entity':{'description':{'identifier':'dead:'+id,'materials':{'default':'entity_alphatest'},'textures':{'default':'textures/entity/zombie/husk' if id=='armored' else 'textures/entity/zombie/zombie'},'geometry':{'default':'geometry.zombie.v1.8'},'animations':{'look_at_target':'animation.common.look_at_target','move':'animation.humanoid.move','base_pose':'animation.humanoid.base_pose','attack':'animation.humanoid.attack.rotations'},'scripts':{'animate':['base_pose','move','look_at_target','attack']},'render_controllers':['controller.render.default'],'spawn_egg':{'base_color':'#4a5742','overlay_color':'#a43d32'}}}})
for f in (RP/'entity').glob('*.json'):
    data=json.loads(f.read_text(encoding='utf-8'));d=data['minecraft:client_entity']['description']
    d['animations']={'walk':'animation.dead.walk'};d['scripts']={'animate':['walk']};write(f,data)
write(RP/'animations/dead.animation.json',{'format_version':'1.8.0','animations':{'animation.dead.walk':{'loop':True,'bones':{'leftLeg':{'rotation':['math.cos(query.modified_distance_moved * 38.17) * query.modified_move_speed * 80',0,0]},'rightLeg':{'rotation':['-math.cos(query.modified_distance_moved * 38.17) * query.modified_move_speed * 80',0,0]},'leftArm':{'rotation':[-75,0,0]},'rightArm':{'rotation':[-75,0,0]}}}}})
print('Generated 5 usable items, 4 infected types and resource pack')
